### PR TITLE
Fix - Attrack Messages

### PR DESCRIPTION
**Pull request by xiaolin1579**

### CODE REVIEW

**Comment by de-luxe** [comment]
Thanks for your effort ... just looking into it right now ... 
Also compiled and uploaded it to 
https://www.dropbox.com/s/sr6izh74kg8siv8/burstcoin-1.2.8-quickfix-xiaolin1579.zip?dl=0

**Comment by lucvanbraekel** [comment]
> should use debug mode to clear unconfirmed transactions once

Can you explain how exactly this is done?
Is ```nxt.debug=true``` enough, or should ```nxt.debugLogUnconfirmed=true``` be added?

**Comment by lucvanbraekel** [comment]
Oh, I see, it's ```nxt.enableDebugAPI=true``` and then call the wallet with ```http://127.0.0.1:8125/test?requestTag=DEBUG``` and click 
Go to http://127.0.0.1:8125/test?requestTag=DEBUG and click ```clearUnconfirmedTransactions```

**Comment by de-luxe** [comment]
@lucvanbraekel @xiaolin1579 
I build and uploaded the 1.2.9b from @dawallet (https://github.com/dawallet/burstcoin) here:
https://www.dropbox.com/s/zuy1xbxh6bbhob9/burstcoin-1.2.9b.zip
It should hopefully fix the unconfirmed transactions issue and makes this pull request obsolete.

**Comment by de-luxe** [comment]
https://forums.burst-team.us/topic/7580/burstcoin-wallet-v1-2-8-with-quickfix-to-blacklist-spam-accounts

**Pull request closed without merging**
